export const UPDATE_MODAL_BUY_TICKET = "UPDATE_MODAL_BUY_TICKET";
export const UPDATE_MONEY = "UPDATE_MONEY";
export const UPDATE_DECEASE_MONEY = "UPDATE_DECEASE_MONEY";
export const UPDATE_TOTAL_AND_CHANGE = "UPDATE_TOTAL_AND_CHANGE ";
export const UPDATE_MODAL_SUCCESS = "UPDATE_MODAL_SUCCESS";
export const UPDATE_MODAL_SUCCESSED = "UPDATE_MODAL_SUCCESSED";
